from classifier import *

clf = SentimentClassifier()

comentarios=["por mas marcas d café que compro al final no hay ninguna que me guste tanto como la de dolce gusto, comprando en paquetes de 3 y con amazon suscribete y ahorra salen muy bien de precio, ademas que siempre puedes hacerte el café mas largo regulando el agua y sigue estando bueno (yo le pongo 3 puntos).","El título es una estafa, en verdad vienen 3 cajas de 16 cápsulas, por tanto 48 cápsulas en total y no 64 como pone en el título. Un timo para atraer compradores. No obstante con 48 capsulas el precio es el mismo que en la web de dolce gusto que si compras 3 cajas te aplican un 20% de descuento.""He probado distintos cafés en cápsula para dolce gusto de distintas marcas, pero ninguno con mejor sabor que el original (lógicamente, este aspecto es subjetivo).","Me encanta este cafe. Es el que siempre compro para mi cafetera Dolce Gusto y lo uso prácticamente a diario.","La máquina es muy bonita pero el café es malísimo. Me arrepiento mucho de haber comprado esta máquina. Mucho mejor Nespresso. El café con leche es malísimo, el Chococcino ni fu ni fa. La cafetera a veces no agujerea bien la cápsula y sale café de por todo. Y me ha pasado varias veces Si te gusta el café huye de ellas Dolce Gusto","La devolví junto a la cafetera Krups porque venían juntas, ya que no me sirve de nada tener las cápsulas sin tener la cafetera. ","No vale para nada sobre todo si tienes otro dispositivo echo. Conecta un sólo altavoz y no más y el emparejamiento hay que ser ingeniero mínimo.Eso si para amazon un 10","Al inicio parece un gran producto, pero tener tantos dispositivos activos, no me ha convencido. Me da problemas con los altavoces Bose. Si activo mis altavoces sin el uso de Alexa, se distorsiona, depende mucho del uso de Alexa. En fin, que lo tengo allí abandonado.","Compra inútil nada recomendable. No me gustó nada y lo devolví, para que funcione necesito emparejarlo con la barra de sonido de mi salón con el consiguiente gasto energético de tener siempre ambos aparatos encendidos. Creo que esperaré a probar el que si trae altavoz integrado, haber si es más útil que este modelo.","Compra inútil nada recomendable. No me gustó nada y lo devolví, para que funcione necesito emparejarlo con la barra de sonido de mi salón con el consiguiente gasto energético de tener siempre ambos aparatos encendidos. Creo que esperaré a probar el que si trae altavoz integrado, haber si es más útil que este modelo. ","Funciona igual q la alexa echo, lo único que va enlazada a un altavoz, en mi caso de forma bluetooth que ha sido muy fácil de enlazar al dispositivo, si tienes la apps en el móvil añades el dispositivo y se conecta de una forma muy fácil. Yo la recomiendo para tenerla en una habitación pequeña tipo despacho, en el trabajo. Mi altavoz es del lild y se ha enlazado perfectamente","Compre este dispositivo para enlazarlo con un altavoz bluetooth y funciona de maravilla.Recomiendo la compra, buen inicio en los asistentes virtuales."] #Data
for i in comentarios:
	print(i + ' ==> %.5f' % clf.predict(i)+ "\n")


